apiVersion: v1
kind: Pod
metadata:
  name: pod-default
  namespace: default
spec:
  serviceAccountName: clement
  containers:
    - image: alpine:3.9
      name: alpine
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: clement-token
  volumes:
    - name: clement-token
      secret:
        secretName: clement-token
