apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: myvolume
    - name: mydebian
      image: debian
      command: ["sleep", "600"]
      volumeMounts:
        - mountPath: /worktmp/
          name: myvolume
    - name: myalpine
      image: alpine
      command: ["sh", "-c", "date >/myjob/index.html"]
      volumeMounts:
        - mountPath: /myjob/
          name: myvolume
  volumes:
    - name: myvolume
      emptyDir: {}
