apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvdata1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvdata2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvdata3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvdata4"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvdata5"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monstatefulset
spec:
  serviceName: svc-dns
  replicas: 4
  selector:
    matchLabels:
      app: monsts
  template:
    metadata:
      labels:
        app: monsts
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        storageClassName: manual
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-dns
  labels:
    app: monginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: monsts # important pour la sélection des pods entrant dans le dns
